data-id="{{ $id }}"
data-course_code="{{$course_code}}"
data-short_name="{{ $short_name }}"
data-description="{{$description}}"
data-terms_condition="{{$terms_conditions}}"
data-comment="{{$comment}}"
data-hours="{{$hours}}"
data-quota="{{$quota}}"
data-start_date="{{ date('d/m/Y', strtotime($start_date))}}"
data-end_date="{{date('d/m/Y', strtotime($end_date))}}"
data-university_id="{{$university_id}}"
data-video_text="{{$video_text}}"
data-video_type="{{$video_type}}"
data-video_code="{{$video_code}}"
data-data_update="{{$data_update_brief}}"
data-tc_file_path= {{ $tc_file_path }}
data-lor_file_path= {{ $lor_file_path }}
data-course_type_id={{ $course_type_id }}
data-master_course_id={{ $master_course_id }}
data-course_edition="{{ $edition }}"
data-cost={{ $cost }}
data-finance_type="{{ $finance_type }}"
data-stage={{ $stage }}
data-status={{ $status }}
data-is_disclaimer={{ $has_disclaimer }}
data-disclaimer_file="{{ $disclaimer_file }}"
data-grade_upload_start_date="{{ date('d/m/Y', strtotime($grade_upload_start_date))}}"
data-grade_upload_end_date="{{ date('d/m/Y', strtotime($grade_upload_end_date))}}"